### ISSUE TITLE
vmux starts only every second time

### ISSUE THREAD

**Issue by pogobanane** [vmuxIO/vmuxIO#48]
something about the cleanup/teardown doesnt tear down some socket correctly

**Comment by gierens** [comment]
Yeah simply adding the shared memory path was bound to cause problems at some point. I'll turn it into to a config parameter, and take care of the cleanup. Thank's for the hint.

**Comment by pogobanane** [comment]
i'm pretty sure every vm needs its own qemu-memory file. 
@gierens for autotest we could use sufficiently unique names assembled from username and VM id for example.

**Comment by gierens** [comment]
Jep, that was the idea :)

**Comment by pogobanane** [comment]
> Deleting /dev/shm/qemu-memory before starting a VM solves this issue but probably causes problems when multiple VMs are using it, VMs also don't boot as fast without the memory already being allocated.
